### ISSUE TITLE
The source code does not work (it does not even enter in KMA210's command mode)

### ISSUE THREAD

**Issue by StoykoDimitrov** [2oran/KMA210#1]
I have tested the source code via my Arduino Uno and it does not work. KMA210 does not even enter the command mode.

**Comment by jrocketfingers** [comment]
Whoa, github seems like a really small place. This repo was pretty much just an attempt to make my father (@2oran) use git instead of sending me code snippets over. Totally forgot about it.

I think we even switched to another angle sensor, but I could ping him about this (not sure he checks github nowadays, hopefully the mail got to him, but still).

Sorry I guess, never thought ill prepared projects can get noticed. Guess it's a rather narrow topic :)

**Comment by StoykoDimitrov** [comment]
Thanks, jrocketfingers, I would appreciate that! :)

**Comment by StoykoDimitrov** [comment]
Meanwhile when you reach out your father could you you please ask him also what is the alternative angle sensor that you have switched to? Is it easier for programming? I am asking because I myself have tried to programm KMA210 without positive result although I think that I am doing everything as per the KMA210's specification/data sheet. I see that other people have difficulties programming KMA210 as well so it seems that we are all missing something that is probably blurred and/or misunderstood in its specification. I haven't found a working programming example for this angle sensor so far.

Thanks for your help in advance! Cheers and send my regards to your father! :)

**Comment by jrocketfingers** [comment]
I haven't had much involvement with the sensor myself, the repo was an attempt to increase involvement. However I do remember the were frequent issues with trying to make the sensor work. As far as I know, the alternative sensor might be quite a bit more expensive, as well as bulkier. I'm still waiting for a response, but I do know it was programmed by short circuiting configuration pins according to the manual. It got solid results, even when at an offset to the axle.

However I'm still waiting for a response, sorry!

**Comment by jrocketfingers** [comment]
Alright, the info came back. This is the sensor http://pdb.turck.de/media/_en/Anlagen/Datei_EDB/edb_1590854_gbr_en.pdf

It's got analog output, and it can either output voltage, or current. It's resilient to the inductive axle piece being offset (KMA210 is not, afaik, it has to be centered rather accurately, and it's a small chip). Overall it seems easier to handle.

**Comment by StoykoDimitrov** [comment]
Thank you for this information, jrocketfingers! Meanwhile can you tell me what happened with the programming of the KMA210? Did you succeeded in programming this angular sensor in the end and if you have - please tell me how?

**Comment by jrocketfingers** [comment]
Ah, I probably wasn't clear, we switched from it _because_ we couldn't make it run, and need another, viable, solution. I would've made sure that we've updated the repo if we had ever solved it!

**Comment by StoykoDimitrov** [comment]
Ok, I see. Thank you for everything, jrocketfingers! You were very kind and helpfull! 
Cheers! :)

**Comment by jrocketfingers** [comment]
No problem, sorry it all took so long. :+1:
